// Auto-generated by make — do not edit
let buildVersion = "1.5.2"
let buildCommit = "9344617"
let buildBranch = "main"
let buildDate = "2026-06-08 13:11:46 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
