// Auto-generated by make — do not edit
let buildVersion = "0.7.1"
let buildCommit = "91b772d"
let buildBranch = "main"
let buildDate = "2026-04-04 08:13:31 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
