// Auto-generated by make — do not edit
let buildVersion = "0.7.8"
let buildCommit = "c173e4f"
let buildBranch = "main"
let buildDate = "2026-04-05 06:17:12 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
